/*
 * tz_lookup.c — GPS-based timezone lookup with DST support
 *
 * Uses a RLE-compressed 0.1° grid generated by generate_tz_data.py.
 * Lookup is O(runs_per_row) — typically <50 iterations, <20µs.
 *
 * License: BSD 3-Clause (Off by One / John Stockdale)
 */

#include "tz_lookup.h"
#include "timezone_data.h"
#include <math.h>

// --- Manual override state ---
static bool     s_manual_mode = false;
static int16_t  s_manual_offset_min = 0;

// --- Helpers ---

// Days in a month (handles leap years)
static int days_in_month(int year, int month) {
    static const int dim[] = {0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
    if (month == 2 && (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)))
        return 29;
    return dim[month];
}

// Day of week for a given date (0=Sunday, 1=Monday, ..., 6=Saturday)
// Uses Tomohiko Sakamoto's algorithm
static int day_of_week(int y, int m, int d) {
    static const int t[] = {0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4};
    if (m < 3) y--;
    return (y + y/4 - y/100 + y/400 + t[m-1] + d) % 7;
}

/**
 * Find the day-of-month for the Nth occurrence of a weekday in a month.
 *
 * @param year   Year
 * @param month  Month (1-12)
 * @param week   1=first, 2=second, ..., 5=last
 * @param dow    Day of week (0=Sunday)
 * @return       Day of month (1-31)
 */
static int nth_weekday_of_month(int year, int month, int week, int dow) {
    if (week == 5) {
        // "Last" occurrence: start from the end of the month
        int last_day = days_in_month(year, month);
        int last_dow = day_of_week(year, month, last_day);
        int diff = (last_dow - dow + 7) % 7;
        return last_day - diff;
    }

    // Nth occurrence: start from day 1
    int first_dow = day_of_week(year, month, 1);
    int first_occurrence = 1 + (dow - first_dow + 7) % 7;
    return first_occurrence + (week - 1) * 7;
}

/**
 * Check if DST is active for a given date and DST rule.
 *
 * For northern hemisphere (start_month < end_month):
 *   DST is active from start date to end date.
 *
 * For southern hemisphere (start_month > end_month):
 *   DST is active from start date to end of year, and
 *   from start of year to end date.
 */
static bool is_dst_active(int year, int month, int day, const tz_dst_rule_t *rule) {
    int start_day = nth_weekday_of_month(year, rule->start_month, rule->start_week, rule->start_dow);
    int end_day = nth_weekday_of_month(year, rule->end_month, rule->end_week, rule->end_dow);

    // Encode current date as a comparable integer: month*100 + day
    int cur = month * 100 + day;
    int start = rule->start_month * 100 + start_day;
    int end = rule->end_month * 100 + end_day;

    if (!rule->southern) {
        // Northern hemisphere: DST active from start to end
        return cur >= start && cur < end;
    } else {
        // Southern hemisphere: DST active from start to year end OR year start to end
        return cur >= start || cur < end;
    }
}

/**
 * Look up region_id from the RLE-compressed grid.
 */
static uint8_t grid_lookup(double lat, double lon) {
    // Clamp to grid bounds
    if (lat < -90.0) lat = -90.0;
    if (lat > 89.99) lat = 89.99;
    if (lon < -180.0) lon = -180.0;
    if (lon > 179.99) lon = 179.99;

    // Convert to grid indices
    int lat_idx = (int)((lat + 90.0) / TZ_RESOLUTION);
    int lon_idx = (int)((lon + 180.0) / TZ_RESOLUTION);

    if (lat_idx >= TZ_LAT_CELLS) lat_idx = TZ_LAT_CELLS - 1;
    if (lon_idx >= TZ_LON_CELLS) lon_idx = TZ_LON_CELLS - 1;

    // Get row offset into RLE data
    uint32_t offset = tz_row_offsets[lat_idx];

    // Scan RLE runs for this row
    int col = 0;
    while (col <= lon_idx) {
        uint8_t value = tz_rle_data[offset];
        uint16_t count = tz_rle_data[offset + 1] | (tz_rle_data[offset + 2] << 8);
        if (col + count > lon_idx) {
            return value;
        }
        col += count;
        offset += 3;
    }

    // Shouldn't reach here, but return region 0 (UTC) as fallback
    return 0;
}

// --- Public API ---

tz_result_t tz_lookup(double lat, double lon, int utc_year, int utc_month, int utc_day) {
    tz_result_t result = {0};

    // Manual override
    if (s_manual_mode) {
        result.total_offset_min = s_manual_offset_min;
        result.std_offset_min = s_manual_offset_min;
        result.dst_offset_min = 0;
        result.has_dst = false;
        result.dst_active = false;
        return result;
    }

    // Grid lookup
    uint8_t region_id = grid_lookup(lat, lon);
    if (region_id >= TZ_NUM_REGIONS) region_id = 0;

    const tz_region_t *region = &tz_regions[region_id];
    result.std_offset_min = region->base_offset_qh * 15;
    result.total_offset_min = result.std_offset_min;

    // Check DST
    if (region->dst_rule_id > 0 && region->dst_rule_id < TZ_NUM_DST_RULES) {
        const tz_dst_rule_t *rule = &tz_dst_rules[region->dst_rule_id];
        result.has_dst = true;

        if (is_dst_active(utc_year, utc_month, utc_day, rule)) {
            result.dst_active = true;
            result.dst_offset_min = rule->dst_offset_qh * 15;
            result.total_offset_min += result.dst_offset_min;
        }
    }

    return result;
}

int16_t tz_get_offset_minutes(double lat, double lon, int utc_year, int utc_month, int utc_day) {
    return tz_lookup(lat, lon, utc_year, utc_month, utc_day).total_offset_min;
}

void tz_set_manual_offset(int16_t offset_min) {
    s_manual_offset_min = offset_min;
    s_manual_mode = true;
}

void tz_set_auto(void) {
    s_manual_mode = false;
}

bool tz_is_manual(void) {
    return s_manual_mode;
}
